# Change these first
owner: Ankr-network # Your GitHub organization or username, where this repository lives
repo: safe-services-status # The name of this repository
skipTopicsUpdate: true
sites:
  - name: Safe Client Gateway
    url: https://gnosis-gateway.metaapesgame.com/health/
  - name: Safe Tx Service (APE Mainnet)
    url: https://gnosis-service-apem.metaapesgame.com/check/
  - name: Safe Tx Service (APE Testnet)
    url: https://gnosis-service-apet.metaapesgame.com/check/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /safe-services-status
  logoUrl: https://docs.gnosis.io/safe/img/gnosis_safe_logo_green.png
  name: Safe Ecosystem Foundation Backend Status
  introTitle: Status for the **Safe Ecosystem Foundation** Backend
  introMessage: Safe Ecosystem Foundation Backend Status
  favicon: https://docs.gnosis.io/safe/img/gnosis_safe_logo_green.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

